In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, f_regression
from sklearn.datasets import load_boston
from sklearn.datasets import load_iris
from numpy import array 
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.pipeline import make_pipeline
from sklearn import svm
from mlxtend.feature_selection import SequentialFeatureSelector as SFS

In [2]:
data_train = pd.read_csv('../1.Dataset/train_cleaned.csv')

In [3]:
print(data_train.head(2))

        dur  spkts  dpkts  sbytes  dbytes         rate  sttl  dttl  \
0  0.000011      2      0     496       0   90909.0902   254     0   
1  0.000008      2      0    1762       0  125000.0003   254     0   

         sload  dload  ...  ct_src_dport_ltm  ct_dst_sport_ltm  \
0  180363632.0    0.0  ...                 1                 1   
1  881000000.0    0.0  ...                 1                 1   

   ct_dst_src_ltm  is_ftp_login  ct_ftp_cmd  ct_flw_http_mthd  ct_src_ltm  \
0               2             0           0                 0           1   
1               2             0           0                 0           1   

   ct_srv_dst  is_sm_ips_ports  label  
0           2                0      0  
1           2                0      0  

[2 rows x 40 columns]


In [4]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82332 entries, 0 to 82331
Data columns (total 40 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   dur                82332 non-null  float64
 1   spkts              82332 non-null  int64  
 2   dpkts              82332 non-null  int64  
 3   sbytes             82332 non-null  int64  
 4   dbytes             82332 non-null  int64  
 5   rate               82332 non-null  float64
 6   sttl               82332 non-null  int64  
 7   dttl               82332 non-null  int64  
 8   sload              82332 non-null  float64
 9   dload              82332 non-null  float64
 10  sloss              82332 non-null  int64  
 11  dloss              82332 non-null  int64  
 12  sinpkt             82332 non-null  float64
 13  dinpkt             82332 non-null  float64
 14  sjit               82332 non-null  float64
 15  djit               82332 non-null  float64
 16  swin               823

In [5]:
y = data_train.label

In [6]:
x = data_train.drop('label', axis = 1)

In [7]:
#x['proto'] = pd.get_dummies

In [8]:
select = SelectKBest(score_func=f_regression, k=30)
z = select.fit_transform(x, y) 
print("After selecting best 30 features:", z)  
filter = select.get_support()
features = x.columns
print("All features:")
print(features)
print(features[filter])

After selecting best 30 features: [[2. 0. 0. ... 1. 2. 0.]
 [2. 0. 0. ... 1. 2. 0.]
 [2. 0. 0. ... 1. 3. 0.]
 ...
 [1. 0. 0. ... 1. 1. 1.]
 [1. 0. 0. ... 1. 1. 1.]
 [2. 0. 0. ... 1. 1. 0.]]
All features:
Index(['dur', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl',
       'sload', 'dload', 'sloss', 'dloss', 'sinpkt', 'dinpkt', 'sjit', 'djit',
       'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt', 'synack', 'ackdat', 'smean',
       'dmean', 'trans_depth', 'response_body_len', 'ct_srv_src',
       'ct_state_ttl', 'ct_dst_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm',
       'ct_dst_src_ltm', 'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd',
       'ct_src_ltm', 'ct_srv_dst', 'is_sm_ips_ports'],
      dtype='object')
Index(['spkts', 'dpkts', 'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload',
       'dloss', 'sinpkt', 'dinpkt', 'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt',
       'synack', 'ackdat', 'smean', 'dmean', 'ct_srv_src', 'ct_state_ttl',
       'ct_dst_ltm', 'ct_src_dport

In [9]:
def recursive_forward_elimintaion(size):
    select = SelectKBest(score_func=f_regression, k=size)
    z = select.fit_transform(x, y) 
    print("After selecting best 30 features:", z)  
    filter = select.get_support()
    features = x.columns
    print("All features:")
    print(features)
    print(features[filter])

In [10]:
recursive_forward_elimintaion(39)

After selecting best 30 features: [[1.1e-05 2.0e+00 0.0e+00 ... 1.0e+00 2.0e+00 0.0e+00]
 [8.0e-06 2.0e+00 0.0e+00 ... 1.0e+00 2.0e+00 0.0e+00]
 [5.0e-06 2.0e+00 0.0e+00 ... 1.0e+00 3.0e+00 0.0e+00]
 ...
 [0.0e+00 1.0e+00 0.0e+00 ... 1.0e+00 1.0e+00 1.0e+00]
 [0.0e+00 1.0e+00 0.0e+00 ... 1.0e+00 1.0e+00 1.0e+00]
 [9.0e-06 2.0e+00 0.0e+00 ... 1.0e+00 1.0e+00 0.0e+00]]
All features:
Index(['dur', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl',
       'sload', 'dload', 'sloss', 'dloss', 'sinpkt', 'dinpkt', 'sjit', 'djit',
       'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt', 'synack', 'ackdat', 'smean',
       'dmean', 'trans_depth', 'response_body_len', 'ct_srv_src',
       'ct_state_ttl', 'ct_dst_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm',
       'ct_dst_src_ltm', 'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd',
       'ct_src_ltm', 'ct_srv_dst', 'is_sm_ips_ports'],
      dtype='object')
Index(['dur', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl',
       'sl

In [11]:
def support_vector_machine(type):
    svm.SVC(kernel=type)

In [12]:
linear = support_vector_machine('linear')

In [13]:
kernel = support_vector_machine('kernel')

In [14]:
# lr = svm.SVC(kernel='linear') 
def backward(lr,k):
    classifier_pipeline = make_pipeline(StandardScaler(),MinMaxScaler(),lr)
    from sklearn.pipeline import make_pipeline
    sfs1 = SFS(classifier_pipeline, 
               k_features=k, 
               forward=False, 
               scoring='neg_mean_squared_error',
               cv=5)
    sfs1.fit(x,y)
    sfs1.subsets_

In [15]:
def forward(lr,k):
    classifier_pipeline = make_pipeline(StandardScaler(),MinMaxScaler(),lr)
    from sklearn.pipeline import make_pipeline
    sfs1 = SFS(classifier_pipeline, 
               k_features=k, 
               forward=True, 
               scoring='r2',
               cv=5)
    sfs1.fit(X,y)
    sfs1.subsets_